### ISSUE TITLE
Action failing due to missing `pixi.lock`

### ISSUE THREAD

**Issue by trallard** [scientific-python/upload-nightly-action#106]
Hey there, we recently bumped the `upload-nightly-action` to v6 in PyData Sphinx theme, though since doing so, this keeps failing on CI 
with the following error:

```
Error: Failed to generate cache key: Error: ENOENT: no such file or directory, open 'pixi.lock'
    at /home/runner/work/_actions/prefix-dev/setup-pixi/ba3bb36eb2066252b2363392b7739741bb777659/dist/index.js:80915:9
```

It seems this is now expecting the project to have a `Pixi.lock file`, I am assuming this is coming from https://github.com/scientific-python/upload-nightly-action/blob/ccf29c805b5d0c1dc31fa97fcdb962be074cade3/action.yml#L32

But this is not documented in the README, so I am not entirely sure. We do not use pixi, so what would then be the alternative? Would it be possible to expose the `locked` option so that the user can set to false in such cases?

**Comment by matthewfeickert** [comment]
@trallard v6.0.0 had a bug so please bump to v6.0.1. Depending on your Dependabot frequency you can either wait for it or use the versions listed in the current README.

**Comment by matthewfeickert** [comment]
I've gone through every project currently listed in https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1960398919 and verified that they either aren't using the action or were on the "right" side of the Dependabot schedule to get the `v0.6.1` update. If they were on `v0.6.0` I've opened a PR to fix.
