### ISSUE TITLE
Can you extend my access to ipykernel ?

### ISSUE THREAD

**Issue by Carreau** [scientific-python/upload-nightly-action#110]
We had a couple of downstream breakage, and I want to publish nightly of it as well. 
I should already have access to IPython. 

Thanks

**Comment by matthewfeickert** [comment]
@Carreau (on phone as in transit, sorry) you just need to be added to a team to give you permissions? Or do you need something else changed/added?

**Comment by matthewfeickert** [comment]
@Carreau Ah sorry. I misread and did a mental `s/ipykernel/ipython/g`. Sure, we can add `ipykernel`. I'll make a team later today and add you to it and then you should be good to go.

**Comment by matthewfeickert** [comment]
@Carreau You should now be able to upload to https://anaconda.org/scientific-python-nightly-wheels/ipykernel.

**Comment by Carreau** [comment]
All good, thanks !
