### ISSUE TITLE
request access for pydata-sphinx-theme

### ISSUE THREAD

**Issue by drammock** [scientific-python/upload-nightly-action#117]
NB: I was actually already granted membership to the pydata-sphinx-theme group yesterday (anaconda username [drmccloy](https://anaconda.org/drmccloy)) by @tupui but then I RTFM and saw that I was supposed to open an issue here, so I'm doing that just for the sake of public record so that folks know that I'm authorized. AFAIC this issue can be immediately closed.

**Comment by Carreau** [comment]
Thanks !

**Comment by Carreau** [comment]
Always happy to have PST as nightly.
