### ISSUE TITLE
Add OpenBLAS

### ISSUE THREAD

**Issue by tupui** [scientific-python/upload-nightly-action#20]
There is a request to add OpenBLAS to our list of nightlies: https://github.com/MacPython/openblas-libs/issues/100

Trying out to do this to have a bit more transparency and trail 😃

**Comment by tupui** [comment]
I am +1 for the record

**Comment by matthewfeickert** [comment]
:rocket:

**Comment by Carreau** [comment]
Awesome. Should we have an issue template with checkboxes that reiterate the tasks that need to be done ? I don't think I have the right to add someone the the org on anaconda.org  but happy to help.

**Comment by tupui** [comment]
The template is a good idea 👍 

For the admins we really need to make a call and discuss 😅 IIRC we are something like 8 at the moment which is I think a bit much (and not saying all folks that should be there are already there.)

**Comment by tupui** [comment]
Alright, thanks all. I created the group and will sync with them for the initial upload and their team.

(FYI here, we are talking with Anaconda folks right now to see how we can improve the UI and security for us. Will keep you posted.)
