### ISSUE TITLE
Remove wheels that are older than a threshold time limit

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/upload-nightly-action#31]
There are some 1 and 2 month old numpy wheels that haven't been identified for removal. They all have `rc1` in their version number, so that may trip up the old wheel removing GHA.

https://anaconda.org/scientific-python-nightly-wheels/numpy/files?page=2

**Comment by matthewfeickert** [comment]
> There are some 1 and 2 month old numpy wheels that haven't been identified for removal.

@seberg as your credentials were used to upload these can you remove them if you think that aren't useful currently? I'd prefer for project maintainers to do this.

> They all have rc1 in their version number, so that may trip up the old wheel removing GHA.

No, the name information is not used beyond the project.

https://github.com/scientific-python/upload-nightly-action/blob/a2ba178f650e68bd6f9d8e2b7d59d16ffd257c29/.github/workflows/remove-wheels.yml#L18-L19

https://github.com/scientific-python/upload-nightly-action/blob/a2ba178f650e68bd6f9d8e2b7d59d16ffd257c29/.github/workflows/remove-wheels.yml#L68-L70

The reason those still exist is that they have been uploading `numpy-2.0.0.dev0` wheels that overwrite the previous one and so they still only have 5 wheels on their project &mdash; the current limit.

So this isn't a bug in the current code, but a new feature request to also remove wheels past a certain time threshold. Seems like a good idea.

**Comment by seberg** [comment]
I have deleted all but the current ones.

**Comment by matthewfeickert** [comment]
Thanks @seberg!

**Comment by bsipocz** [comment]
Ahh, OK. This case, we should maybe have another, time-limit logic in the cleanup script, too. E.g. delete everything that is ~month old? At that point I think we can argue that it's not really a nightly build, but something broken.

**Comment by matthewfeickert** [comment]
Yeah 1 month seems very reasonable. 👍

**Comment by bsipocz** [comment]
hah, I see that you already modified the issue here to reflect that. Thanks!

**Comment by matthewfeickert** [comment]
Asked about how much datetime metadata we can get from Anaconda Cloud easily over on https://github.com/Anaconda-Platform/anaconda-client/issues/682.
