### ISSUE TITLE
exclude openblas-libs from the cleanup job

### ISSUE THREAD

**Issue by mattip** [scientific-python/upload-nightly-action#34]
The files at https://anaconda.org/scientific-python-nightly-wheels/openblas-libs/files are not meant to be cleaned up automatically. We generate those tarballs (which are not conda packages) for long-term use by SciPy and NumPy. Is there a way to exclude them from https://github.com/scientific-python/upload-nightly-action/blob/main/.github/workflows/remove-wheels.yml ? If not we should go back to keeping them at https://anaconda.org/multibuild-wheels-staging/openblas-libs/

CC @honno, @rgommers

**Comment by mattip** [comment]
It seems there is a retention policy for packages that the remove-wheels github action implements. Perhaps the policy could be added to [SPEC-04](https://scientific-python.org/specs/spec-0004/) and the [org description](https://anaconda.org/scientific-python-nightly-wheels) could add some detail or point to the SPEC.

**Comment by matthewfeickert** [comment]
> Is there a way to exclude them from https://github.com/scientific-python/upload-nightly-action/blob/main/.github/workflows/remove-wheels.yml ?

The technical answer is easy. Just after

https://github.com/scientific-python/upload-nightly-action/blob/2b318b62a3436c8e05b7ed8d169a6feff8e9b537/.github/workflows/remove-wheels.yml#L52-L56

insert

```
sed -i '/openblas-libs/d' package-names.txt
```

as part of the "Query package index for packages" step.

> It seems there is a retention policy for packages that the remove-wheels github action implements.

The question of if packages that aren't meant to be removed and aren't actually nightlies should be housed here or not seems related to Issue #30.

**Comment by matthewfeickert** [comment]
@mattip @honno Can you confirm that all the versions that are current uploaded (`v0.3.23-246-g3d31191b`, `v0.3.23-293-gc2f4bdbb`, and `HEAD`) are needed currently needed?


![Screenshot from 2023-08-15 14-25-29](https://github.com/scientific-python/upload-nightly-action/assets/5142394/209a1062-a73e-4608-be20-9b123bb7c76b)

@bsipocz has already assigned herself to this Issue (:+1:), but I just wanted to get this clarified as if `v0.3.23-246-g3d31191b` need to be guarded (some of the uploads for that version are 28 days old today) this should be done with a 1 liner PR quickly to avoid any issues while the discussion of where non-nightly things live is had.

**Comment by mattip** [comment]
The opnblas-libs are more like PyPI artifacts, in that various versions of NumPy and Scipy will ask for various versions of these artifacts. The versions are specified in a script, [here](https://github.com/numpy/numpy/blob/4387e03d7d00d1277b01424acc6b3fa66141c0fb/tools/openblas_support.py#L17) for NumPy and [here](https://github.com/scipy/scipy/blob/c20c60f2a149c314611b02aff5652ad5665132b4/tools/openblas_support.py#L17) for Scipy (which is still using the old site for the non-nightly version). Version `v0.3.23-246-g3d31191b` is the one used by the previous version of the script for NumPy/main, and as far as I can tell is not used by any active branches or release tags.

This discussion is one more reason to turn the openblas tarballs into wheels, see MacPython/openblas-libs#86.

**Comment by mattip** [comment]
My request still stands: please exclude openblas-libs from the cleanup job, regardless of ongoing conversations about whether the use of this site is a good fit for openblas-libs. I may be wrong about the need for the artifact about to be deleted, and it would be a shame to break somebody's build.

**Comment by matthewfeickert** [comment]
:wave: @mattip The [`openblas-libs`](https://anaconda.org/scientific-python-nightly-wheels/openblas-libs) files are currently using 4.6 GB out of the org's (current) total 20 GB and 3.4 GB worth of those files have never been downloaded.

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/f5b3a858-550a-4540-895c-3ef757dee3d0)

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/e12f1158-26bc-4e45-88ff-4c1f68aa6bbf)

This is currently fine, but as you asked that all automated removal of the files be excluded for these files, what is the `openblas-libs`'s team's plan for curation of the files?

**Comment by mattip** [comment]
Once https://github.com/numpy/numpy/pull/25505 goes in, and a similar PR can be made to SciPy, we will stop uploading tarballs and only upload wheels (scipy-openblas64 and scipy-openblas32).

**Comment by matthewfeickert** [comment]
> I don't think the wheels (at scipy-openblas64 and scipy-openblas32) were ever reserved artifacts, only the tarballs, right?

Right.

> The tarballs (at openblas-libs) will still be used by older builds of maintenance versions and by third-party projects for a while.

Okay, I think this answers my question, thanks. There can be some natural phase out period where at some future point (would you project 1 year as reasonable?) the tarballs can be removed, and then just the wheels can remain and those can get cycled at the same rates as the rest of the projects. :+1:

**Comment by matthewfeickert** [comment]
Congratulations @mattip to you and the rest of the team on getting https://github.com/numpy/numpy/pull/25505 in! :tada: That seems like a heroic amount of work that has been done, but seems exciting.

For those of us who haven't been fully tracking this work (i.e. me) and its ramifications for NumPy and SciPy wheels, can you or @rgommers give just a bullet list, to compliment https://github.com/scientific-python/upload-nightly-action/issues/34#issuecomment-1929006404, of what this means moving forward for what will get uploaded to the [scientific-python-nightly-wheels](https://anaconda.org/scientific-python-nightly-wheels) Anaconda org, and what Issues or PRs interested parites should be watching?

I think the answer to the first part, given https://github.com/scientific-python/upload-nightly-action/issues/34#issuecomment-1929006404, is that we should soon expect there to be no new [`openblas-libs`](https://anaconda.org/scientific-python-nightly-wheels/openblas-libs) uploads and that the only future uploads will be [`scipy-openblas64`](https://anaconda.org/scientific-python-nightly-wheels/scipy-openblas64) and [`scipy-openblas32`](https://anaconda.org/scientific-python-nightly-wheels/scipy-openblas32) wheels. Though what is the projected timeline for that? (now? in a few weeks? next release?)

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/ac2cecdf-4fa0-443c-a0b8-c6376e7e61de)
