### ISSUE TITLE
CI: revisit 30day cut-off for cleanup

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/upload-nightly-action#35]
Now rereading the discussion in #4, consensus was more generous with the cutoff age of wheel removal, we should therefore change the currently implemented 30 to a much longer period.

**Comment by matthewfeickert** [comment]
> Agreed, I would give 3 to 6 months to be more generous with "slower" projects. But we could start with a lower bar and revisit if the use case ever comes up. &mdash; https://github.com/scientific-python/upload-nightly-action/issues/4#issuecomment-1569280605

@tupui do you still feel this way? Or are you fine with 1 month as it is now?

https://github.com/scientific-python/upload-nightly-action/blob/2b318b62a3436c8e05b7ed8d169a6feff8e9b537/.github/workflows/remove-wheels.yml#L64

**Comment by tupui** [comment]
Sorry for the delay, I was away 😃

I think the current config is ok for now. We can keep it that way until we have a request.

**Comment by matthewfeickert** [comment]
Thanks @tupui. @bsipocz, are you good with closing this then?

**Comment by matthewfeickert** [comment]
Closing as this hasn't had any new feedback since 2023-08-25 and there have been no complaints raises. This can be reopened if needed.
