### ISSUE TITLE
bot autoupdating downstream to new url

### ISSUE THREAD

**Issue by martinfleis** [scientific-python/upload-nightly-action#39]
While discussing the change of the home for nightlies, @bsipocz mentioned that once all core packages are uploading to a new location, there is a way to automatically open PRs downstream, changing the url from the old scipy one to the new scientific-python. 

@bsipocz was there an attempt to do that? I haven't noticed it in any of the packages I'm involved with. Given the scipy repository is now outdated, it would be good to roll this out. I understood that all the necessary pieces were ready.

**Comment by matthewfeickert** [comment]
> there is a way to automatically open PRs downstream, changing the url from the old scipy one to the new scientific-python.

I may be wrong, but my understanding was that this would be done by people (maybe scripted) but not using a GitHub Actions workflow.

> I haven't noticed it in any of the packages I'm involved with.

@martinfleis can you please link all the projects you want updated here?

**Comment by martinfleis** [comment]
> my understanding was that this would be done by people

My understanding was that a bot can do this and that @bsipocz knows how to deploy that bot.

> but not using a GitHub Actions workflow.

Probably not by GHA. I am not sure. I may be raising the question in the wrong repo...

> can you please link all the projects you want updated here that fit the current definitons of "core" 

It is not about core packages, it is about the TEST WITH NIGHTLY WHEELS part of the [SPEC 4](https://scientific-python.org/specs/spec-0004/). A lot of non-core downstream packages were already testing against nightly wheels uploaded to `pypi.anaconda.org/scipy-wheels-nightly`. All those need to be updated. I can update those I maintain but there is a ton of maintainers not aware of the change. The bot should've resolved that.

**Comment by matthewfeickert** [comment]
> My understanding was that a bot can do this 

Okay great.

> It is not about core packages, it is about the TEST WITH NIGHTLY WHEELS part of the [SPEC 4](https://scientific-python.org/specs/spec-0004/).
> ...
> All those need to be updated. I can update those I maintain but there is a ton of maintainers not aware of the change. The bot should've resolved that.

Okay. A thing to note is that the example given in SPEC 4 leaves people open to possible security issues (that should get fixed) and the pattern given in 

https://github.com/scientific-python/upload-nightly-action/blob/ae4395280cc54a849801b0db1d19bbcb816341f2/README.md?plain=1#L65-L70

(i.e. the index is `scientific-python-nightly-wheels` and the extra index is PyPI) should be used instead.

**Comment by matthewfeickert** [comment]
I'm going to close this as I think all users are now on the correct URL, but please comment if this isn't the case for anyone.

**Comment by bsipocz** [comment]
There are still a lot of github search finds for the old URL, but a large fraction are coming from old travis config files, etc, so it makes sense to close this issue as an autobot would just create a good amount of noise at this point.

**Comment by bsipocz** [comment]
I go ahead and reopen this issue given the more recent feelings around the numpy 2.0 release, apparently ~90ish non-fork repos still have the old link in their [tox.ini](pypi.anaconda.org/scipy-wheels-nightly path:tox.ini  NOT is:archived  NOT is:fork) and ~30 in their [.github](pypi.anaconda.org/scipy-wheels-nightly path:.github  NOT is:archived  NOT is:fork). Having a quick look at least a part of those repos are legit: still maintained and indeed not forks or manual copies.
