### ISSUE TITLE
Request access for scipy-openblas32 and scipy-openblas64

### ISSUE THREAD

**Issue by mattip** [scientific-python/upload-nightly-action#42]
Please allow uploading the new openblas-as-wheel package to the nightly build site.

**Comment by mattip** [comment]
See https://github.com/MacPython/openblas-libs/issues/86 for a bit of the background to the issue, and the current implementations in the PyPI wheels https://pypi.org/project/scipy-openblas32/ and https://pypi.org/project/scipy-openblas64/. The idea is to package OpenBLAS as a wheel that can be installed separately from NumPy, SciPy. Allowing access would make it more convenient to test newer wheels.

**Comment by mattip** [comment]
Also see the first comment on numpy/numpy#24749 for a rough draft of how a developer would use these wheels at build-time and runtime.

**Comment by tupui** [comment]
To be clear, you want to have both `scipy-openblas32` and `scipy-openblas64`? Or just `scipy-openblas`?

**Comment by mattip** [comment]
We need both. The wheels are named scipy-openblas32 and scipy-openblas64 to differentiate the IPL64 interfaces.

**Comment by mattip** [comment]
> can you DM me the handles

Done, via Quansight slack

**Comment by tupui** [comment]
Both https://anaconda.org/scientific-python-nightly-wheels/scipy-openblas32 and 
https://anaconda.org/scientific-python-nightly-wheels/scipy-openblas64 were created and admins of the OpenBLAS added as admin for the packages.

Let us know if you need anything else.

Note that these are "packages" as opposed to https://anaconda.org/scientific-python-nightly-wheels/openblas-libs which is not marked as such. I am not sure why (this is different from everything else) and it makes it hard to manage as the UI does not immediately show non "packages".

cc @jarrodmillman we only see everything in the storage section https://anaconda.org/scientific-python-nightly-wheels/settings/storage

**Comment by mattip** [comment]
Thanks!

**Comment by bsipocz** [comment]
@mattip - Am I right to assume that these should be exempt from the automated cleanup (after 30days)?

**Comment by mattip** [comment]
No, these are “regular” wheel packages and not to be treated differently than other projects. If we need them to live more than 30 days we should upload them to PyPI or testpypi
