### ISSUE TITLE
Action breaks with python 3.12 - clyent/anaconda-client

### ISSUE THREAD

**Issue by MridulS** [scientific-python/upload-nightly-action#43]
Anaconda client uses clyent which uses `imp`. The `imp` module has been removed from python 3.12

The clyent package exists in something called the graveyard https://github.com/anaconda-graveyard/clyent which doesn't sound nice.

**Comment by Carreau** [comment]
Any traceback ? SO we can see what need to be fixed where ?

**Comment by Carreau** [comment]
Copy pasting as logs are not kept forever:

```
Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    from binstar_client.scripts.cli import main
  File "/opt/conda/lib/python3.12/site-packages/binstar_client/__init__.py", line 19, in <module>
    from . import errors
  File "/opt/conda/lib/python3.12/site-packages/binstar_client/errors.py", line 3, in <module>
    from clyent.errors import ClyentError
  File "/opt/conda/lib/python3.12/site-packages/clyent/__init__.py", line 5, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by Carreau** [comment]
Opened upstream https://github.com/Anaconda-Platform/anaconda-client/issues/689

**Comment by dalcinl** [comment]
Folks, looks like that `import imp` line is stale, the `imp` module is not used anywhere in the package. Maybe this can be fixed by patching sources and bumping the build number in the conda-forge/clyent-feedstock repo to get a new fresh package that works in Python 3.12 (assuming there are no other incompatibilities, of course).

**Comment by matthewfeickert** [comment]
This is an example of why I opened https://github.com/scientific-python/upload-nightly-action/pull/32

**Comment by matthewfeickert** [comment]
@MridulS @jarrodmillman now that PR #32 has been merged, can you please trigger a workflow dispatch run of `networkx`'s [`nightly` pipeline](https://github.com/networkx/networkx/blob/692e8d236e2ac3b1f0963da728cae72bbd4715d2/.github/workflows/nightly.yml)?

If that passes as I would expect now then I will close this Issue and make a `0.2.0` release.

**Comment by MridulS** [comment]
works now :) Thanks!
