### ISSUE TITLE
Request access for DIPY

### ISSUE THREAD

**Issue by skoudoro** [scientific-python/upload-nightly-action#45]
Hi Scientific Python Team,

Please allow uploading the DIPY wheel packages to the nightly build site. We are currently building our wheels in this repo: https://github.com/MacPython/dipy-wheels

Thank you 

EDIT: we might switch to cibuildwheel next year.

**Comment by matthewfeickert** [comment]
@skoudoro has this been discussed with the [SPEC Steering Committee](https://scientific-python.org/specs/steering-committee/)? Currently I believe that only packages that are defined as "[core](https://scientific-python.org/specs/core-projects/)" are being given upload permissions to the channel (c.f. https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1671963420 and Issue #29).

**Comment by stefanv** [comment]
@skoudoro Are there many packages that depend on a DiPy wheel for testing? That may be motivation to include it.

**Comment by skoudoro** [comment]
> @skoudoro has this been discussed with the [SPEC Steering Committee](https://scientific-python.org/specs/steering-committee/)?

No, I did not know that I need to do a request to the steering commitee first

> Currently I believe that only packages that are defined as "[core](https://scientific-python.org/specs/core-projects/)" are being given upload permissions to the channel (c.f. https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1671970218 and Issue https://github.com/scientific-python/upload-nightly-action/issues/29).

ok, thank you for letting me know. I believed it was for all scientific package and an alternative to the previous one  https://anaconda.org/scipy-wheels-nightly/  where we had our nightly build.

> @skoudoro Are there many packages that depend on a DiPy wheel for testing? That may be motivation to include it.

Not sure, about that, when I look at the download of our previous nightly build repo, it seems only few packages were using it: https://anaconda.org/scipy-wheels-nightly/dipy/files.

**Comment by skoudoro** [comment]
Thank you @matthewfeickert, I will read the thread. 

Also, what do you recommend as an alternative for now @matthewfeickert and @stefanv ?

**Comment by martinfleis** [comment]
I may not be up to speed with the recent discussions but original idea was not limited to core projects. We wanted to replace the scipy nightly channel so any package that is compiled and used by a wider community could be included.

**Comment by skoudoro** [comment]
No worries and thank you for clarifying.  I understand also the anaconda space challenge.

For now, I will go ahead and use github as a nightly wheels storage like cython project. 

I am closing this issue since I feel it is a duplicate of #29 and #30.  

Just keep me updated if there is some progress concerning this point.

Thank you all and Happy thanksgiving week!

**Comment by matthewfeickert** [comment]
@skoudoro I'm going to leave this open so that the SPEC authors can respond here (unless @bsipocz and @jarrodmillman want to continue this discussion where it originally started in Issue #29 or was moved to in Issue #30).

**Comment by jarrodmillman** [comment]
The main issue is how much space anaconda is willing to give us. I asked a friend whether they could ask for more space since they know people at anaconda. I will make another request and see if we can get more space.

**Comment by betatim** [comment]
Modulo space limits (I didn't realise there was a limit) I'd say that in general all packages that have a track record of being maintained and used should be eligible.

**Comment by jarrodmillman** [comment]
![2023-11-23T05:57:19,257587432-08:00](https://github.com/scientific-python/upload-nightly-action/assets/123428/e3a1a58a-f63e-470d-b26e-f0c07c50c9f0)

**Comment by skoudoro** [comment]
That's a great news! thank you for following up with that!

I will do it a bit later today and keep you updated.

Thanks!

**Comment by skoudoro** [comment]
all good, closing
