### ISSUE TITLE
Allow a new inputs parameter named `anaconda_nightly_upload_url`

### ISSUE THREAD

**Issue by skoudoro** [scientific-python/upload-nightly-action#46]
Hi Scientific Python Team, 

is it possible to add the optional input `anaconda_nightly_upload_url`.

Instead of creating a different fork, I would like to reuse this action for another anaconda repo (DIPY nightly wheels)

it would be great to have also the optional input label (manage anaconda label).

Let me know what you think, if it is possible to do that here or if I should fork and maintain an alternative version.

thank you for the feedback.

**Comment by matthewfeickert** [comment]
I had originally raised this idea in Issue #8, but it was rejected then for the reasons discussed there. 

I would be in favor of this, but before opening a PR let's ping @betatim and @bsipocz to see if they have different views now.

**Comment by stefanv** [comment]
From that discussion, it's not clear there was a use-case. Also, it didn't look like @betatim or @bsipocz had strong reservations.

**Comment by bsipocz** [comment]
I would fully support this feature, the more packages using the action the better it is for the ecosystem. (My only reservations in the past was about the SP anaconda space and therefore to limit it to core libraries, or at least test it in practice and preferably work out policies before opening it up for domain packages)

**Comment by skoudoro** [comment]
Thank all for the feedback.

It seems everyone is positif so I just created a PR(https://github.com/scientific-python/upload-nightly-action/pull/47) to follow up on this.
