### ISSUE TITLE
Request to add two members to the SciPy team on anaconda.org

### ISSUE THREAD

**Issue by rgommers** [scientific-python/upload-nightly-action#49]
Hi team, I'd like to request that an admin adds the following anaconda.org user names to the SciPy team:

- `treddy` (SciPy release manager, GitHub handle @tylerjereddy)
- `andyfaff` (most active CI and wheel build machinery maintainer for SciPy, GitHub handle @andyfaff)

These two folks, together with me, are the most likely to need access and take actions like manually deleting broken wheels (something that just came up on https://github.com/scipy/scipy/issues/19713).

Side note: I wasn't 100% sure that this is the right repo for this request, but it's the closest match in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects.

**Comment by tupui** [comment]
Hi Ralf, this is the right place to ask.

You three are now members of the package.
