### ISSUE TITLE
Request access for `sunpy`

### ISSUE THREAD

**Issue by nabobalis** [scientific-python/upload-nightly-action#50]
Hello!

We (over at the sunpy project) want to provide a nightly wheel for our core package, `sunpy`.
I think we might come under the definition of core, at least within our little ecosystem in solar physics. Packages like astropy's reproject I think have CI that checks against dev sunpy, so a wheel there would be helpful. 

Would it be possible to gain access?

Happy Holidays.

**Comment by matthewfeickert** [comment]
👋 Thanks for the Issue. This is the right place to raise such a request, but we're unfortunately still deciding how to address them. Please join the discussion over on Issue #45.

(Apologies for the short response. I'm traveling at the moment and have a broken computer so I'm stuck on GitHub's mobile app till I fix that.)

**Comment by bsipocz** [comment]
I think it would make a lot of sense to do an openastronomy registry and serve wheels for sunpy, astropy, pyerfa, etc from there, as these are way less core packages in the sense of the whole ecosystem than e.g. awkward et al. But they are clearly and definitely domain ones.

**Comment by bsipocz** [comment]
That said, we should definitely go ahead and merge #47 as soon as possible, so the infrastructure can be shared and reused even for a different registry

**Comment by nabobalis** [comment]
Where would we host an openastronomy registry?

Happy to get involved in helping that if possible.

**Comment by bsipocz** [comment]
on anaconda, just as it's done for liberfa and astropy atm.

**Comment by nabobalis** [comment]
Makes sense to me. I see there is an https://anaconda.org/openastronomy I just need an access token to start uploading? I need to look at the workflow and see how it works.

**Comment by matthewfeickert** [comment]
@nabobalis Good news, we have the approval (https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1960037619) to add `sunpy` to the nightly wheels Anaconda Cloud org https://anaconda.org/scientific-python-nightly-wheels/ !

To get started on this can you please do the following:

## Steps to gain upload access to https://anaconda.org/scientific-python-nightly-wheels/

* [ ] Create an account on [Anaconda Cloud](https://anaconda.org/)
* [ ] Reply here with the link to your account
* [ ] Make a new Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/697ce89f-4a51-43d0-a26f-2493f4bdce34)

* [ ] Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`
* [ ] Direct me (@matthewfeickert) to a `sunpy` nightly wheel for me to upload to create the package in the registry
* [ ] Verify that I have added you to the [`sunpy` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/sunpy) on https://anaconda.org/scientific-python-nightly-wheels
* [ ] Verify that I have added the package `scientific-python-nightly-wheels/sunpy` to the [`sunpy` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/sunpy)

If you'd also like to use the `scientific/upload-nightly-action` GitHub Action that this repository provides please check out [this repo's README](https://github.com/scientific-python/upload-nightly-action?tab=readme-ov-file#nightly-upload). If you need to collect wheels from different CI jobs, consider creating a new GitHub Actions workflow with logic similar to [`matplotlib`'s](https://github.com/matplotlib/matplotlib/blob/88d64e5f0cc82a050b840e61ac60e1081bb6d799/.github/workflows/nightlies.yml) or [`Awkward`'s](https://github.com/scikit-hep/awkward/pull/3012).

If you have any questions please just ask here!

**Comment by nabobalis** [comment]
> @nabobalis Good news, we have the approval ([#30 (comment)](https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1960037619)) to add `sunpy` to the nightly wheels Anaconda Cloud org [anaconda.org/scientific-python-nightly-wheels](https://anaconda.org/scientific-python-nightly-wheels/) !

Thank you!

> ## Steps to gain upload access to [anaconda.org/scientific-python-nightly-wheels](https://anaconda.org/scientific-python-nightly-wheels/)
> * [X]  Create an account on [Anaconda Cloud](https://anaconda.org/)
> * [X]  Reply here with the link to your account

Would a sunpy (non-personal) account be ok? https://anaconda.org/sunpy/

> * [X]  Make a new Anaconda Cloud API token with permissions described in [scientific-python.org/specs/spec-0004/#process-for-adding-new-projects](https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects)
> * [X]  Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`
> * [X]  Direct me (@matthewfeickert) to a `sunpy` nightly wheel for me to upload to create the package in the registry

Hopefully a dropbox link is ok: https://www.dropbox.com/scl/fi/mvauudyw1fihh1pegvy4n/sunpy-6.0.dev213-gbf6eb5884-cp310-abi3-linux_x86_64.whl?rlkey=vjlkynjuw1l5gmqlvq0310vix&dl=0

Our cron CI is having some issues at the moment.

> * [ ]  Verify that I have added you to the [`sunpy` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/sunpy) on [anaconda.org/scientific-python-nightly-wheels](https://anaconda.org/scientific-python-nightly-wheels)
> * [ ]  Verify that I have added the package `scientific-python-nightly-wheels/sunpy` to the [`sunpy` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/sunpy)

**Comment by matthewfeickert** [comment]
> Would a sunpy (non-personal) account be ok? https://anaconda.org/sunpy/

@nabobalis What matters is that the API token is associated with the account. Is the API token you currently use associated with the `sunpy` org account?

I used the wheel you linked me to create the project https://anaconda.org/scientific-python-nightly-wheels/sunpy, so once we have the info on the account+API token pair to use then you should be good to start uploading.

**Comment by nabobalis** [comment]
> > Would a sunpy (non-personal) account be ok? [anaconda.org/sunpy](https://anaconda.org/sunpy/)
> 
> @nabobalis What matters is that the API token is associated with the account. Is the API token you currently use associated with the `sunpy` org account?

Yes it is. 

> I used the wheel you linked me to create the project [anaconda.org/scientific-python-nightly-wheels/sunpy](https://anaconda.org/scientific-python-nightly-wheels/sunpy), so once we have the info on the account+API token pair to use then you should be good to start uploading.

**Comment by matthewfeickert** [comment]
@nabobalis Okay great. As long as you can see https://anaconda.org/scientific-python-nightly-wheels/groups/sunpy when logged in on the `sunpy` account then you should be good to go. :+1:

**Comment by nabobalis** [comment]
> @nabobalis Okay great. As long as you can see [anaconda.org/scientific-python-nightly-wheels/groups/sunpy](https://anaconda.org/scientific-python-nightly-wheels/groups/sunpy) when logged in on the `sunpy` account then you should be good to go. 👍

If I access that page, "I get You don't have permission to view this page." when I am logged into the sunpy account.

**Comment by matthewfeickert** [comment]
> If I access that page, "I get You don't have permission to view this page." when I am logged into the sunpy account.

Hm. Let me look into that but, the `sunpy` account has all the permissions for the `sunpy` group as other accounts do, so even if you can't see the group for some reason you should be able to upload to it.

> Our cron CI is having some issues at the moment.

Once your build job is working again can you try to do an upload and then report back here?

**Comment by nabobalis** [comment]
Will do. Thank you again.

**Comment by nabobalis** [comment]
So we changed our CI, I hope correctly to upload:

https://github.com/sunpy/sunpy/pull/7456

When our cronjob is back, we will hopefully find out if I added the correct token!

**Comment by nabobalis** [comment]
We restored our cron and it worked: https://anaconda.org/scientific-python-nightly-wheels/sunpy/files 

Thank you again for giving us access. I have updated the job (https://github.com/sunpy/sunpy/pull/7457/files) to (hopefully) keep the lastest wheel only. Hopefully we will not fill up your storage space.

**Comment by stefanv** [comment]
Great! And no worries about storage; as long as we delete old wheels we'll be fine.
