### ISSUE TITLE
Port example GitHub Action to `nightly-wheels`

### ISSUE THREAD

**Issue by matthewfeickert** [scientific-python/upload-nightly-action#6]
I have a GitHub Action that is an example version of what the scope of this one needs to be at https://github.com/matthewfeickert/example-nightly-wheels (this will probably get deleted in the future). This should get ported over and get tests setup with full integration (so being able to publish should be part of that step).

@ogrisel how difficult was it to get the https://anaconda.org/scipy-wheels-nightly/ org? If it didn't require too much then I might attempt to get a `scientific-python` account that could be used for testing of uploads. Perhaps there is a way to mock out GitHub Actions, but I'm not exactly sure how that would work.

**Comment by bsipocz** [comment]
This issue was opened on another repo, and in practice, this repo ``upload-nightly-action`` does provide the action and libraries are using it to upload to https://anaconda.org/scientific-python-nightly-wheels/.
