### ISSUE TITLE
Request access for shapely

### ISSUE THREAD

**Issue by jorisvandenbossche** [scientific-python/upload-nightly-action#63]
While not a core project, Shapely is widely used in geospatial subcommunity. Shapely is a compiled package, and apart from an external dependency on GEOS, it also has a build dependency on numpy, so especially with the upcoming numpy 2.0 it would be nice to host shapely nightly wheels built with numpy 2.0.

(I see there is some discussions in other issues about criteria when to include a package, tried to reflect that in the above paragraph)

cc @martinfleis

**Comment by matthewfeickert** [comment]
@jorisvandenbossche Good news, we have the approval (https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1960037619) to add `shapely` to the nightly wheels Anaconda Cloud org https://anaconda.org/scientific-python-nightly-wheels/ !

To get started on this please do the following:

## Steps to gain upload access to https://anaconda.org/scientific-python-nightly-wheels/

* [ ] Create an account on [Anaconda Cloud](https://anaconda.org/)
* [ ] Reply here with the link to your account
* [ ] Make a new Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/697ce89f-4a51-43d0-a26f-2493f4bdce34)

* [ ] Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`
* [ ] Verify that I have added you to the `Shapely` team "Group" on https://anaconda.org/scientific-python-nightly-wheels

If you'd also like to use the `scientific/upload-nightly-action` GitHub Action that this repository provides please check out [this repo's README](https://github.com/scientific-python/upload-nightly-action?tab=readme-ov-file#nightly-upload). If you need to collect wheels from different CI jobs, consider creating a new GitHub Actions workflow with logic similar to [`matplotlib`'s](https://github.com/matplotlib/matplotlib/blob/88d64e5f0cc82a050b840e61ac60e1081bb6d799/.github/workflows/nightlies.yml) or [`Awkward`'s](https://github.com/scikit-hep/awkward/pull/3012).

If you have any questions please just ask here!

**Comment by jorisvandenbossche** [comment]
> * Direct me (@matthewfeickert) to a `shapely` nightly wheel for me to upload to create the package in the registry

The wheels are built on github actions, and so for the currently last commit on main, you can find it here: https://github.com/shapely/shapely/actions/runs/7931478835 (scroll down to the artifacts, and then download the wheels for any of the architectures should work I guess)

**Comment by jarrodmillman** [comment]
Would it make sense to add geopandas as well?

**Comment by matthewfeickert** [comment]
@jorisvandenbossche I've made https://anaconda.org/scientific-python-nightly-wheels/shapely/ and you should now have admin control over the [shapely group](https://anaconda.org/scientific-python-nightly-wheels/groups/shapely). If you've created the API token then you should now be able to have your CI/CD workflow upload. :+1:

**Comment by martinfleis** [comment]
@jarrodmillman Geopandas is pure Python. Do we want to include packages like that as well? It won't take almost any space, that's for sure.

**Comment by stefanv** [comment]
If it's pure Python, then CI can install directly from GitHub. I think it makes most sense to have binary artifacts in this repo.

**Comment by jorisvandenbossche** [comment]
Thanks a lot @matthewfeickert ! 
Verified that I was added to the anaconda cloud account, and set up the upload action on the shapely side (https://github.com/shapely/shapely/pull/1997, https://github.com/shapely/shapely/pull/1998), the first set of wheels have been uploaded.
