### ISSUE TITLE
Have networkx use a personal token over org token

### ISSUE THREAD

**Issue by matthewfeickert** [scientific-python/upload-nightly-action#68]
@MridulS @jarrodmillman It looks like `networkx` is still uploading to https://anaconda.org/scientific-python-nightly-wheels using the org token.

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/e827bcac-a895-46d1-b140-8390025f65f4)

Can we get you to switch to using a personal token? To do so we just need at least one of you (you're both admins of the [`NetworkX` group](https://anaconda.org/scientific-python-nightly-wheels/groups/NetworkX)) to do the following steps:

1. Make a new personal Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/697ce89f-4a51-43d0-a26f-2493f4bdce34)

2. Save the API token as the repo GitHub Actions secret [`networkx` currenlty has named `ANACONDA_NIGHTLY`](https://github.com/networkx/networkx/blob/8cffd1e7004a94be4556121cc3aff442772542d0/.github/workflows/nightly.yml#L32)

Let me know here if you have any questions. :+1:

**Comment by MridulS** [comment]
Thanks for the ping! the action is using my personal token now :)
