### ISSUE TITLE
Document that the action requires to run on ubuntu

### ISSUE THREAD

**Issue by jorisvandenbossche** [scientific-python/upload-nightly-action#71]
I naively added the action to our cibuildwheel matrix (for the shapely wheels), expecting to upload the wheels from each OS-specific build directly. 
However, this does not work because the action apparently requires a linux image: *"Container action is only supported on Linux"* (see eg https://github.com/shapely/shapely/actions/runs/8047467718/job/21976750565). So you need to gather all wheel for the different architectures and upload them from another job running on ubuntu.

**Comment by matthewfeickert** [comment]
Ah yes. I hadn't thought about that, but as it is [container based](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action), it currently requires a Linux OS base.

This should get documented in the README as you suggest.

**Comment by matthewfeickert** [comment]
Note to self: c.f. https://github.com/shapely/shapely/pull/1998
