### ISSUE TITLE
Have scikit-image use a personal token over org token

### ISSUE THREAD

**Issue by matthewfeickert** [scientific-python/upload-nightly-action#72]
@jarrodmillman @stefanv It looks like `scikit-image` is still uploading to https://anaconda.org/scientific-python-nightly-wheels using the org token.

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/5fdc7722-7dd6-4f70-9b26-3dc6dfe0d567)

Can we get you to switch to using a personal token? To do so we just need at least one of you (you're both admins of the [`scikit-image` group](https://anaconda.org/scientific-python-nightly-wheels/groups/scikit-image)) to do the following steps:

1. Make a new personal Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/697ce89f-4a51-43d0-a26f-2493f4bdce34)

2. Save the API token as the repo GitHub Actions secret [`scikit-image` currenlty has named `UPLOAD_TOKEN`](https://github.com/scikit-image/scikit-image/blob/0278ab335dd2868a2a805e3dbe6f7eea887da590/.github/workflows/nightly_wheel_build.yml#L43)

Let me know here if you have any questions. :+1:

**Comment by stefanv** [comment]
Thanks @matthewfeickert for the ping! I've uploaded the token. It expires a year from now.

**Comment by matthewfeickert** [comment]
Great and thanks! Closing now.
