### ISSUE TITLE
BUG: Failed wheel upload for h5py

### ISSUE THREAD

**Issue by larsoner** [scientific-python/upload-nightly-action#77]
After most of the h5py binaries uploading successfully last night the 3.11 one failed:

https://github.com/h5py/h5py/actions/runs/8445531348/job/23133109268#step:5:408

```
Warning:  Distribution "h5py-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" already exists. Removing.
Creating package "h5py"
Creating release "3.10.0"
Uploading file "scientific-python-nightly-wheels/h5py/3.10.0/h5py-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"

  0%|          | 0.00/5.17M [00:00<?, ?B/s]
  0%|          | 16.0k/5.17M [00:00<01:04, 83.8kB/s]
  2%|▏         | 128k/5.17M [00:00<00:10, 507kB/s]  
  9%|▉         | 496k/5.17M [00:00<00:03, 1.63MB/s]
 22%|██▏       | 1.14M/5.17M [00:00<00:01, 3.26MB/s]
 61%|██████▏   | 3.17M/5.17M [00:00<00:00, 8.93MB/s]
5.18MB [00:00, 6.13MB/s]                            
standard python located at:
  https://anaconda.org/scientific-python-nightly-wheels/h5py

Error:  ("Invalid dist_id ObjectId('6603800020b28178c3fabc66') does not exist", [404](https://github.com/h5py/h5py/actions/runs/8445531348/job/23133109268#step:5:405))
```

Any ideas on what the problem could? Could the upload be made more robust somehow? It removed the wheel built the previous night prior to trying to upload the new wheel, so I ended up with a failed `--pre` install on a Linux 3.11 CI.

**Comment by matthewfeickert** [comment]
@larsoner Looks like you didn't try to rerun the workflow. Please do that (by which I mean just select the rerun button from the GitHub UI).

**Comment by larsoner** [comment]
No permissions to restart myself so I'll probably just wait 24h for the next nightly :)

Closing since it does seem to be an upstream bug!

**Comment by matthewfeickert** [comment]
I opened up https://github.com/Anaconda-Platform/anaconda-client/issues/712 for this.

**Comment by larsoner** [comment]
Yeah I think @tacaswell or @takluyver should be able to restart this job (copied from above for convenience) to fix the incomplete nightly wheel upload:

https://github.com/h5py/h5py/actions/runs/8445531348/job/23133109268#step:5:408

**Comment by takluyver** [comment]
I've hit restart, it seems to have succeeded now. :+1:
