### ISSUE TITLE
Request access for pydata-sphinx-theme

### ISSUE THREAD

**Issue by larsoner** [scientific-python/upload-nightly-action#82]
@matthewfeickert I made some progress following your checklist from #80:

* [x] Create an account on [Anaconda Cloud](https://anaconda.org/)
* [x] Reply here with the link to your account: https://anaconda.org/larsoner/dashboard
* [x] Make a new Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects
* [x] Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`
* [x] Direct me (@matthewfeickert) to a `pydata-sphinx-theme` nightly wheel for me to upload to create the package in the registry: 

   I created one with `python -m build -w` on latest `main` just now and uploaded it [here](https://www.dropbox.com/scl/fi/1xxglr18u0kwifr13ap0h/pydata_sphinx_theme-0.15.4.dev0-py3-none-any.whl?rlkey=uu5zbi9fh60kpwavi7ndkzu0c&dl=0).

* [x] Verify that I have added you to the [`pydata-sphinx-theme` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/cython) on https://anaconda.org/scientific-python-nightly-wheels
* [x] Verify that I have added the package `scientific-python-nightly-wheels/pydata-sphinx-theme` to the [`pydata-sphinx-theme` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/cython)

Let me know if you need other stuff! I assume adding this package is uncontroversial 🙂  And I talked to @drammock who maintains PST and am adding CI infra in https://github.com/pydata/pydata-sphinx-theme/pull/1867.

**Comment by tupui** [comment]
I will do the next steps now 😃

**Comment by tupui** [comment]
@larsoner all done

You should have admin access to:
https://anaconda.org/scientific-python-nightly-wheels/pydata-sphinx-theme

So using your Anaconda personal token should allow you to upload new wheels 😃 

FYI you can manually test in the CLI with

```
anaconda -t sc-... upload -u scientific-python-nightly-wheels pydata_sphinx_theme-...-py3-none-any.whl
```

Closing, but let me know if anything is not working.

**Comment by larsoner** [comment]
Awesome thanks @tupui !
