### ISSUE TITLE
Request access for Pillow

### ISSUE THREAD

**Issue by lysnikolaou** [scientific-python/upload-nightly-action#84]
Hi all, with the ongoing work that's going on for porting pillow to free-threaded Python, it makes sense to us that it uploads nightly wheels as well, since it's a dependency for scikit-image, which is already in the list of projects that do so.

Pillow issue: https://github.com/python-pillow/Pillow/issues/8199

cc @hugovk

**Comment by tupui** [comment]
Thanks 🙏 I am +1.

You know the drill now is it comes through 😉

**Comment by bsipocz** [comment]
Pillow would be great to have!

**Comment by lysnikolaou** [comment]
Great! @hugovk Can you please complete the check list? (taken from the Cython issue)

- [ ] Create an account on [Anaconda Cloud](https://anaconda.org/)
- [ ] Reply here with the link to your account
- [ ] Make a new Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects
- [ ] Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`

A set of pillow wheels for the project to be created can be found [here](https://github.com/python-pillow/Pillow/actions/runs/9922723702).

**Comment by radarhere** [comment]
https://anaconda.org/radarhere

**Comment by tupui** [comment]
Thanks folks, I will do the creation steps later today and ping you here.

**Comment by tupui** [comment]
You are all set @hugovk @radarhere 🚀 

Thanks @lysnikolaou for the work in the background.

Let us know if you need any support 😃

**Comment by tupui** [comment]
https://anaconda.org/scientific-python-nightly-wheels/pillow

**Comment by matthewfeickert** [comment]
Thanks @hugovk @lysnikolaou @radarhere and @tupui for moving fast on this!

@hugovk @radarhere If you'd also like to use the [`scientific/upload-nightly-action` GitHub Action](https://github.com/scientific-python/upload-nightly-action) please check out [the action repo's README](https://github.com/scientific-python/upload-nightly-action?tab=readme-ov-file#nightly-upload). If you need to collect wheels from different CI jobs, consider creating a new GitHub Actions workflow with logic similar to [`matplotlib`'s](https://github.com/matplotlib/matplotlib/blob/88d64e5f0cc82a050b840e61ac60e1081bb6d799/.github/workflows/nightlies.yml) or [`Awkward`'s](https://github.com/scikit-hep/awkward/pull/3012).

**Comment by hugovk** [comment]
Please could you also @aclark4life? 

https://anaconda.org/aclark

re: https://github.com/python-pillow/Pillow/pull/8236#issuecomment-2233050364

**Comment by aclark4life** [comment]
> Please could you also @aclark4life?
> 
> https://anaconda.org/aclark
> 
> re: [python-pillow/Pillow#8236 (comment)](https://github.com/python-pillow/Pillow/pull/8236#issuecomment-2233050364)

@lysnikolaou Thank you!

**Comment by tupui** [comment]
Done folks 😃
