### ISSUE TITLE
Storage and potential cleanup

### ISSUE THREAD

**Issue by tupui** [scientific-python/upload-nightly-action#85]
We are still good, but some projects might take a bit too much resources. Seems like openblas-lib passed 500 files and is around 10GB. That sounds too much to me 😅 

<img width="738" alt="Screenshot 2024-07-15 at 21 19 11" src="https://github.com/user-attachments/assets/e6762f1e-9217-43f5-bc42-6f5b5ca1672f">

**Comment by tupui** [comment]
For openblas-lib, we also have this:

<img width="776" alt="Screenshot 2024-07-15 at 21 22 01" src="https://github.com/user-attachments/assets/1ec0e6e7-cd8f-476a-ad82-a337dc032649">

**Comment by matthewfeickert** [comment]
Yeah, they had asked to not have their binaries removed but I think it is reasonable to ask them to select some for removal when hitting 10 GB. Though if they really need it we could give them the space.

**Comment by tupui** [comment]
yeah I mean here it shows that 8.2 GB were never touched...

**Comment by bsipocz** [comment]
Cc @mattip

**Comment by matthewfeickert** [comment]
> yeah I mean here it shows that 8.2 GB were never touched... 😅

Ah, sorry I was replying from my phone and so I only saw the text, not the image.

Yeah, @mattip, can you comment a bit in response to https://github.com/scientific-python/upload-nightly-action/issues/34#issuecomment-1937941294 on what files of these are actively needed?

**Comment by mattip** [comment]
Since we have wheels available, I think there is no need for the openblas-libs tarballs anymore. I submitted a PR to the repo that is uploading them to stop doing that.

**Comment by matthewfeickert** [comment]
Thanks @mattip! Once https://github.com/MacPython/openblas-libs/pull/164 is merged I'll go ahead and remove the openblas-libs tarballs, unless you indicate that there are any particular releases that you still need.

**Comment by tupui** [comment]
Great thanks 🙏

**Comment by mattip** [comment]
You can remove the tarballs.

**Comment by matthewfeickert** [comment]
Thanks @mattip! Sorry for the slow response, but I've been on holiday hiking without internet access.

I've removed the tarballs and as we're now using under 1/4 of the total storage we have I will also close this Issue.

![image](https://github.com/user-attachments/assets/103a65fe-c47b-469b-9c1e-e5ad1d744038)
