### ISSUE TITLE
pyproj access

### ISSUE THREAD

**Issue by snowman2** [scientific-python/upload-nightly-action#87]
- https://anaconda.org/snowman2
- https://github.com/pyproj4/pyproj/issues/1316

Please let me know what the next steps are. Thank you!

**Comment by matthewfeickert** [comment]
@snowman2 please complete the missing items from the checklist to get started.

* [x] Create an account on [Anaconda Cloud](https://anaconda.org/)
* [x] Reply here with the link to your account (https://anaconda.org/snowman2)
* [ ] Make a new Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/697ce89f-4a51-43d0-a26f-2493f4bdce34)

* [ ] Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`
* [ ] Direct me (@matthewfeickert) to a `pyproj` nightly wheel for me to upload to create the package in the registry
* [ ] Verify that I have added you to the [`pyproj` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/pyproj) on https://anaconda.org/scientific-python-nightly-wheels
* [ ] Verify that I have added the package `scientific-python-nightly-wheels/pyproj` to the [`pyproj` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/pyproj)

If you'd also like to use the [`scientific/upload-nightly-action` GitHub Action](https://github.com/scientific-python/upload-nightly-action) please check out [the action repo's README](https://github.com/scientific-python/upload-nightly-action?tab=readme-ov-file#nightly-upload). If you need to collect wheels from different CI jobs, consider creating a new GitHub Actions workflow with logic similar to [`matplotlib`'s](https://github.com/matplotlib/matplotlib/blob/88d64e5f0cc82a050b840e61ac60e1081bb6d799/.github/workflows/nightlies.yml) or [`Awkward`'s](https://github.com/scikit-hep/awkward/pull/3012).

If you have any questions please just ask here!

**Comment by snowman2** [comment]
@matthewfeickert, there are some wheels in the artifacts from this build: https://github.com/pyproj4/pyproj/actions/runs/10125914197

**Comment by matthewfeickert** [comment]
Thanks @snowman2. I've posted one of the wheels to create the project at https://anaconda.org/scientific-python-nightly-wheels/pyproj so now the only thing left is for you to add the Anaconda Cloud API token to the https://github.com/pyproj4/pyproj/ repo GitHub Actions secrets and start uploading wheels.

Once you're able to do a successful scheduled upload then we can resolve this issue. :+1:

**Comment by snowman2** [comment]
It worked, thank you 👍
