### ISSUE TITLE
NumPy tokens have expired

### ISSUE THREAD

**Issue by mattip** [scientific-python/upload-nightly-action#90]
I am not sure who are the numpy project admins. The token has expired, as can be seen in [this workflow](https://github.com/numpy/numpy/actions/runs/10756493112/job/29829413389#step:6:378) and [this workflow](https://github.com/numpy/numpy/actions/runs/10756487678/job/29829405767#step:11:39) cc numpy/numpy#27339. There are two tokens: NUMPY_STAGING_UPLOAD_TOKEN and NUMPY_NIGHTLY_UPLOAD_TOKEN.

**Comment by matthewfeickert** [comment]
@mattip This is a NumPy issue, not a upload-nightly-action issue. Please ask @rgommers @tylerjereddy and @seberg to make new tokens via `https://anaconda.org/<anaconda cloud user name>/settings/access`.

**Comment by matthewfeickert** [comment]
Though you can see by looking at https://anaconda.org/scientific-python-nightly-wheels/numpy/files 

![image](https://github.com/user-attachments/assets/c0a9852b-8b59-4ab6-a622-1e561a0b2305)

that @seberg's token was being used for the uploads. So if you want that to stay the same, @seberg please regenerate the tokens and update the relevant NumPy GitHub Actions secrets.

**Comment by mattip** [comment]
> Please ask ...

I think you just did :)

**Comment by matthewfeickert** [comment]
> I think you just did :)

Indeed. :) Though you might have more direct channels than I do, so if so, and this is time sensitive please convey the information there also.

**Comment by tylerjereddy** [comment]
@mattip is it urgent or can it wait for i.e., Sebastian on Monday?

**Comment by mattip** [comment]
Not urgent, thanks.

**Comment by stefanv** [comment]
Do we have a way of checking who has access to renew tokens? I have permission to set tokens on gh/numpy, but not generate them on anaconda.org.

**Comment by seberg** [comment]
Sorry, I created a new token now.  I think we set up a token for NumPy with my account but never added a second admin with access to the NumPy nightlies upload.
(Which doesn't seem like a huge deal, since I think adding a second person is easy, if I was MIA for longer, but also happy to just add e.g. Matti.)

**Comment by seberg** [comment]
Ah, didn't realize that we already had 3 people, that seems plenty.  Anyway, just added a token, it'll expire in a year+some (maybe should have done longer), and updated it in NumPy repo, plus the PR for Cirrus.

I think we didn't notice the upload was failing for a while, which seems like the bigger annoyance then actually (it's OK if they fail for 1-2 weeks or so IMO, but not nice to miss for a month)

**Comment by stefanv** [comment]
On github.com/notifications, I've set up a custom filter with `reason:ci-activity`. This shows me all failed runs. Not perfect, but it's something.

**Comment by matthewfeickert** [comment]
> Do we have a way of checking who has access to renew tokens? I have permission to set tokens on gh/numpy, but not generate them on anaconda.org.

@stefanv (sorry was answering on phone earlier so missed this)

(I might be telling you things you already know but) people are given admin privileges to individual project groups (https://anaconda.org/scientific-python-nightly-wheels/groups) that allow tokens generated by them to have upload access, but they generate the tokens on their personal Anaconda Cloud accounts

https://github.com/scientific-python/upload-nightly-action/blob/b3d150d89b9500cd5623f211d6214f1d8b50fac5/README.md?plain=1#L39-L45

(The people that have the ability to generate tokens for the scientific-python-nightly-wheels Anaconda Cloud org are in the Owners group &mdash; which includes you &mdash; but those tokens are for admin reasons and aren't/should not be used for uploading nightly wheels from any projects.)

**Comment by matthewfeickert** [comment]
As I see that the uploads for https://anaconda.org/scientific-python-nightly-wheels/numpy/files are working again with @seberg's token I'm going to close this issue.

![image](https://github.com/user-attachments/assets/f71a8277-42ab-44f0-9e2b-d71a747ce7d4)

Though if people have additional comments or questions please ask them here so that we can clarify things and/or create new issues to improve the process.

**Comment by mattip** [comment]
Is there a reason to have a 1 year expiration time for the token?

**Comment by tupui** [comment]
Security. 1 year is already extremely generous for what this token can do in the wrong hands.

**Comment by stefanv** [comment]
It's quite painful to rotate tokens, though. It would be helpful if we had a script that a maintainer could run, that would e.g. connect via OAuth, to generate tokens and set them where necessary. This would be a good tool for SP to provide, if `gh` can't do it already.

**Comment by stefanv** [comment]
(According to SPEC 6, these procedures, and who have access to them, should be documented. But not much progress on that front yet.)

**Comment by charris** [comment]
> I think we didn't notice the upload was failing for a while

I got messages that the `emscripten` upload failed and opened an issue the second time it happened. I don't know why none of the other failed uploads sent me a message.

**Comment by tupui** [comment]
Yeah I've seen these attempts at a few companies now and the best solution I've seen, as in the thing which team can rely on in the long run, is an entry in a calendar 😅 There are plenty of tools to help with that too, just yet another thing to have configured.

**Comment by bsipocz** [comment]
> I got messages that the emscripten upload failed and opened an issue the second time it happened. I don't know why none of the other failed uploads sent me a message.

Unfortunately, failing cron CI statuses in GHA are not consistent to send notifications.

**Comment by matthewfeickert** [comment]
> It seems that the upload procedure should ping someone on failure, maybe that can be configured.

@charris Failing GitHub Actions jobs already send emails. What sort of additional notifications that something went wrong were you thinking about?
